version: '3.5'

services:
  db:
    image: citelibre/rendezvous:db-1.0.14-SNAPSHOT
    container_name: rdv_db
    ports:
      - "3307:3306"
    # if you want to persist data uncomment the following 2 lines... don't forget to create the directory mysql-data for sample
    #volumes:
    #    - ./mysql-data:/var/lib/mysql

  solr:
    image: citelibre/rendezvous:solr-1.0.14-SNAPSHOT
    container_name: rdv_solr
    command: -force
    depends_on:
      - db
    ports:
      - "8983:8983"
    # if you want to persist data uncomment the following 4 lines
    #volumes:
    #  - type: volume
    #    source: solr-data
    #    target: /var/solr/data/cite-libre/data

  mailpit:
    image: axllent/mailpit:v1.18.3
    container_name: rdv_mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 1080:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 500
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
          
  matomo:
    image: citelibre/rendezvous:matomo-1.0.14-SNAPSHOT
    container_name: rdv_matomo
    ports:
      - "80:80"
    depends_on:
      - solr

  keycloak:
    image: citelibre/rendezvous:keycloak-1.0.14-SNAPSHOT
    container_name: rdv_keycloak
    ports:
      - "8081:8080"
    depends_on:
      - db

  citelibre:
    image: citelibre/rendezvous:ihm-1.0.14-SNAPSHOT
    container_name: rdv_citelibre
    ports:
      - 8080:8080
    depends_on:
      - solr
    environment:
      - LUTECE_DB_USER
      - LUTECE_DB_PWD
      - LUTECE_DB_NAME 
      - LUTECE_DB_HOST 
      - LUTECE_DB_PORT 
      - LUTECE_MAIL_HOST
      - LUTECE_MAIL_PORT
      - LUTECE_MAIL_USER
      - LUTECE_MAIL_PWD
      - LUTECE_INTERNAL_KEYCLOAK=true
    mem_limit: 2g
    volumes:
      - type: volume
        source: rendezvous-data
        target: /usr/local/tomcat/webapps/rendezvous

  kibana:
    image: citelibre/rendezvous:kibana-1.0.14-SNAPSHOT
    container_name: rdv_kibana
    environment:
      - discovery.type=single-node
      - server.publicBaseUrl=localhost
    ports:
      - 5601:5601
    mem_limit: 1g
    depends_on:
      - elasticsearch
        #volumes:
        #  - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  elasticsearch:
    image: citelibre/rendezvous:elasticsearch-1.0.14-SNAPSHOT
    container_name: rdv_elasticsearch
    environment:
      - ELASTIC_PASSWORD="*93n2US7fWog"
      - discovery.type=single-node
      - ESJAVAOPTS=-Xmx1g
      - xpack.security.enabled=false
    mem_limit: 1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data

volumes:
  elasticsearch-data:
  rendezvous-data:
    #  solr-data:
